sudo: required
services:   
    - docker

before-install:
    - docker build -t nitinrai17/docker-react -f Dockerfile.dev . 
    
script:
    - docker run -e CI=true nitinrai17/docker-react npm run test -- --coverage
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-117771544263"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY2"
    secret_access_key:
        secure: "$AWS_SECRET_KEY2"
        
        
        
        
        
    