sudo: required
services:   
    - docker

before-install:
    - docker build -t nitinrai17/docker-react -f Dockerfile.dev . 
    
script:
    - docker run nitinrai17/docker-react npm run test -- --coverage